services:
  # consul 注册中心、配置中心
  consul:
    image: hashicorp/consul:1.16.1
    container_name: consul
    ports:
      - 8500:8500
    command:
      - agent
      - -server
      - -ui
      - -node=server-1
      - -bootstrap-expect=1
      - -client=0.0.0.0
